# 指定生效的配置文件
spring:
  profiles:
    active: prod
  # 404交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  mail:
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: false
  servlet:
    # 文件上传上限
    multipart:
      max-file-size: 200Mb
      max-request-size: 200Mb

# 通用配置
# ################################
# windows
file_path: D:\opt\upload
# linux
#file_path: \opt\upload
